### ISSUE TITLE
Aufgabe 2.html?

### ISSUE THREAD

**Issue by ratnanil** [windijon/Patterns-Trends-ZHAW#1]
Hey Jonas!

Your repo is looking good! We will take a closer look in the next few days. In the meantime, can you also push Aufgabe 2.html to your repo? If you haven't created this file yet, you can do so by "knitting" Aufgabe 2.Rmd.

Btw: I would not add spaces in your filenames, this can cause all sorts of issues!

See you in the exercise soon!

Nils

**Comment by windijon** [comment]
Issues solved. Html is also uploaded on my repo.
