### ISSUE TITLE
Html file?

### ISSUE THREAD

**Issue by ratnanil** [windijon/Patterns-Trends-ZHAW#2]
I see there is no 'html' file in your repo. In case you are working with Rmarkdown, creating an html file is very simple. Simpliy 'render' the document using the 'Render' Button or the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>\n\n PS: This issue was generated automatically.

**Comment by windijon** [comment]
There is a html file called "Aufgabe_2.html" (https://github.com/windijon/ZHAW-Patterns-Trends-Exercise2/blob/main/Aufgabe_2.html)
