### ISSUE TITLE
Don't include "View()" in your analysis

### ISSUE THREAD

**Issue by ratnanil** [windijon/Patterns-Trends-ZHAW#3]
Since `View()` only works in an interactive session, you should remove this from your analysis to enable rendering your document to html.

https://github.com/windijon/ZHAW-Patterns-Trends-Exercise2/blob/5dbcf2c048a71fa2efc32271c13b0600e385079b/Aufgabe_2.Rmd#L28

**Comment by ratnanil** [comment]
https://github.com/windijon/ZHAW-Patterns-Trends-Exercise2/blob/5dbcf2c048a71fa2efc32271c13b0600e385079b/Aufgabe_2.Rmd#L112

**Comment by ratnanil** [comment]
https://github.com/windijon/ZHAW-Patterns-Trends-Exercise2/blob/5dbcf2c048a71fa2efc32271c13b0600e385079b/Aufgabe_2.Rmd#L123

**Comment by windijon** [comment]
solved issues, uploaded new files
