### ISSUE TITLE
Remove verbose messages from your output html

### ISSUE THREAD

**Issue by ratnanil** [windijon/Patterns-Trends-ZHAW#4]
Just some cosmetics: You can add the option `message = FALSE` to remove all verbose messages in the output html.

To do so, replace this line

https://github.com/windijon/ZHAW-Patterns-Trends-Exercise2/blob/5dbcf2c048a71fa2efc32271c13b0600e385079b/Aufgabe_2.Rmd#L12

with this:

```
{r message = FALSE}
```

**Comment by windijon** [comment]
solved issues, uploaded new files
